apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: ksops-secret
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secret/encrypt-config.yaml